export * from './forget-password/forget-password'
export * from './login/login'
export * from './signup/signup'
export * from './home/home'
export * from './contact/contact'
export * from './about/about'
export * from './error/error'
export * from './manage-account/manage-account'